### PR TITLE
Support non-period separated Addresses when unmarshaling.

### PR DESCRIPTION
**Pull request by rspier**
Also, split out Address.String() tests.
Expand unmarshaling tests.  (Uppercase hex too!)

### CODE REVIEW

**Comment by abates** [comment]
Thanks for the pull request.  The only issue I have with it is that testAddressString is not capitalized and, therefore, will not be run.

Please capitalize testAddressString and I will merge the request.

**Comment by rspier** [comment]
Whoops.  Fixed!

**Comment by abates** [comment]
Thanks so much for the pull request!  Let me know what you think of the package.

Regards,
Andrew

**Comment by rspier** [comment]
I like it.  It's having a little bit of trouble retrieving the all link databases for devices (as opposed to the PLM) which I'll dig into at some point.  Other libraries are working fine, if slowly.  I'm hoping to use this to configure my switches instead of the sadly discontinued HomeLinc (which I can't seem to make work in VirtualBox.)

**Comment by abates** [comment]
When it doesn't retrieve the link database does it get anything at all?  The TTL is hard coded to 2 [here](https://github.com/abates/insteon/blob/cf9c8f9add007c110a843a450217f4b7386894bb/message.go#L75-L84), whereas most Insteon devices send messages with a TTL set to 3.  If you have high attenuation (distance, interference, etc) and messages must be repeated more often, then I think this might cause a problem.

**Comment by rspier** [comment]
It doesn't appear to be the TTL.  More discussion https://github.com/abates/insteon/issues/2

**Pull request merged**
